Metaswitch/pjsip-upstream

pjsip/include/pjsip/sip_config.h
pjsip/include/pjsip/sip_transport_tcp.h
pjsip/src/pjsip/sip_transport_tcp.c

Steve,
Please can you review my fix to the TCP connection timeout aspect of https://github.com/Metaswitch/sprout/issues/1018?  (You're probably most ramped up on it.)
The key bits are
*   `tcp_create`, where we set up the timer
*   `lis_create_transport`, where we start it running
*   `tcp_connect_timer`, which handles the timer popping and generates a connection timeout event.
I've tested live.  Unfortunately, there aren't any UTs for this.
A corresponding sprout change will follow shortly.
Matt

[Reviewer: Steve] Add configurable TCP connect timeout timer

---

pjlib/include/pj/compat/socket.h
pjlib/include/pj/sock.h
pjlib/src/pj/sock_bsd.c
pjlib/src/pj/sock_common.c
pjsip/include/pjsip/sip_config.h
pjsip/include/pjsip/sip_transport_tcp.h
pjsip/src/pjsip/sip_transport_tcp.c

Alex,
Please can you review this enhancement to add a configurable SIP send timeout?  It's basically just plumbing through to the `setsockopt` call.
Thanks,
Matt

[Reviewer: Alex] Add configurable SIP send timeout

---

pjsip/src/pjsip/sip_auth_msg.c

Previously, if no username was specified, the Authorization header was invalid - it had a comma between "Digest" and the first parameter.
This just re-orders it, so that the 'response' parameter (always unconditionally printed) comes first. Tested live.

[Reviewer: Alex] Avoid generating invalid digest credentials

---

pjsip/src/pjsip/sip_msg.c

Rob,
Please can you review this fix to https://github.com/Metaswitch/sprout/issues/1170 to drop the support for the PJSIP-proprietary "hide" parameter?  I've UT-ed in the sprout codebase (which will follow shortly).
Thanks,
matt

[Reviewer: Rob] Drop support for PJSIP-proprietary "hide" parameter

---

aconfigure
third_party/srtp/crypto/cipher/aes_icm.c
third_party/srtp/crypto/math/datatypes.c

(I've started compiling with clang - it's faster and gives more warnings - so I'm fixing up the issues that come out of the woodwork.)
This gets PJSIP building with clang - one is the fix mentioned in https://freeswitch.org/jira/si/jira.issueviews:issue-html/FS-6196/FS-6196.html, the other just updates a line of code which filters "gcc" out to also filter "clang" and "clang-3.6".

[Reviewer: Alex] Fixes for clang interop

---

pjsip/src/pjsip/sip_transport.c
pjsip/src/pjsip/sip_transport_tcp.c

[Reviewer AMC] Handle missing content-length header in TCP packets by dropping the connection to avoid hanging that connection indefinitely.
Tested in sprout UTs and by feeding corrupt SIP in directly using sipp.  Also ran Clearwater Live Tests against the new code as sanity check.

[Reviewer AMC] Handle missing content-length header in TCP packets

---

pjlib/src/pj/activesock.c
pjlib/src/pj/ioqueue_common_abs.c
pjlib/src/pj/ioqueue_common_abs.h
pjsip/src/pjsip/sip_transport_tcp.c

This adds the concept of "write-only concurrency" to PJSIP, to release the transaction lock before calling the write callback (but *not* before calling the read callback) and prevent us from deadlocking if the write callback takes a transport lock. Basically as you suggested in https://github.com/Metaswitch/sprout/issues/1088.

[Reviewer: Matt] Allow concurrent writes

---

pjlib/include/pj/config_site.h

Set the config option in PJSIP to disable UDP to TCP uplift.

[Reviewer: RKD] Disable UDP to TCP uplift.

---

pjlib/include/pj/config_site.h

TCP uplift is now configurable so revert to having TCP uplift enabled by default.

[Reviewer: RKD] Re-enable TCP uplift

---

pjsip/include/pjsip/sip_msg.h
pjsip/include/pjsip/sip_parser.h
pjsip/src/pjsip/sip_msg.c
pjsip/src/pjsip/sip_parser.c

Refactored parse_generic_array_hdr to allow for an arbitrary delimiter. This is to allow the delimiter in a privacy header to be a semicolon rather than a comma, as per issue #1514.

[Reviewer: RJW2] Refactoring the parsing of generic_array_hdr to allow for non-comma delimiters.

---

pjsip/include/pjsip/sip_msg.h
pjsip/src/pjsip/sip_msg.c

Rob,
This exposes some methods from PJSIP which we need to correctly implement Privacy header printing.

[Reviewer: RKD] Expose pjsip_generic_array_header_clone methods

---

pjlib/include/pj/string.h
pjlib/include/pj/string_i.h

Currently there's no way in pjsip to construct a pj_str_t from a constant buffer and length. The other pj_strdup() functions either assume you have a pj_str_t, or have a C style null terminated buffer. This adds another version which takes both a buffer and a length.

[Reviewer: Ellie] Allow dupe of string from const buffer and length

---

pjsip/include/pjsua-lib/pjsua.h
pjsip/src/pjsua-lib/pjsua_core.c

Otherwise pjsua sits there for 5 minutes trying to initialize audio devices on systems that don't have any.

Add option to bypass media init in PJSUA for applications which only care about signaling.

---

pjsip/include/pjsip/sip_auth.h
pjsip/src/pjsip/sip_auth_server.c

Sathiyan, please can you review this change to refactor the pjsiop authentication API so it can be used with raw messages rather than rdatas. This is a non-backwards compatible change as the API as the fields on `pjsip_auth_lookup_cred_param` have changed. I'm not too worried as we're the only ones using this repo and I couldn't think of a good way of maintaining backwards compatibility.

Refactor authentication API to allow it to be used with messages rather than rdatas

---

pjsip/include/pjsip/sip_transport.h
pjsip/src/pjsip/sip_transport.c
pjsip/src/pjsip/sip_transport_tcp.c

There is a problem with how pjsip deals with transport errors that affects that type of routing that is only generally performed in a BGCF.  When pjsip hits a transport error while sending a SIP INVITE over TCP, it notifies sprout, which internally generates a SIP 503 response.  This response is notified up to the sproutlet, which may choose to try sending that INVITE via an alternative route.  If the second route has the same next first hop (e.g. both the primary and secondary routes go via the local IBCF), then pjsip will attempt to reuse the failed transport (see below for why).  Retrying on a failed transport does not produce the same notfications up to the application, so the second attempt will hang until the inbound SIP transaction times out.
pjsip has a mechanism for shutting down …

[Reviewer: EM] Mark failed transports to avoid reuse

---

pjlib/src/pj/lock.c
pjsip/include/pjsip/sip_transaction.h
pjsip/src/pjsip/sip_transaction.c

Mat,
Please can you review my fix to https://github.com/Metaswitch/sprout/issues/1727?  That issue was that a transaction was being destroyed between the transaction hash table (in which it was being looked up) being unlocked and the transaction's own lock being taken.  (It's not possible to take the lock on the transaction while the transaction hash table is locked because this could cause deadlock.)
The bulk of this fix is to increment the reference count on the group lock while the lock on the transaction hash table is held (this is legal, and stops the transaction from being destroyed) and then decrement the reference count once the group lock has actually been taken.  To allow for the case where the transaction has been flagged as destroyed (i.e. all its child resources have been …

[Reviewer: Mat] Close transaction destruction race condition

---

pjsip/include/pjsip/sip_util.h
pjsip/src/pjsip/sip_util.c

This PR adds a method to PJSIP to create an ACK to a negative response using a `pjsip_msg` instead of a `pjsip_rx_data`.
Needed for the sproutlet API change I'm making.

[Reviewer: AJH] Add method to generate ACK from msg

---

pjsip/src/pjsip/sip_parser.c

Rob,
Could you review this fix to allow us to accept headers (particularly the Supported: header) with a trailing comma?  Passing direct to you since you've looked at this already - hope that's OK.
Neil

[Reviewer: RKD] Allow list headers to have a trailing comma

---

pjsip/src/pjsip/sip_tel_uri.c

Allow a Tel URI to have non-digit characters (as these are valid if the Tel URI is a wildcard)

[Reviewer: Krista] Fix up allowed chars in a Tel URI

---

pjlib-util/src/pjlib-util/xml.c

print_node always gets its return code checked elsewhere, but in this case it was added to a positive number before being checked, so a -1 return code may not be caught.
Add in the check, no test written as it's in pjsip.

[Reviewer: RJW2] Check return code of print node.

---

aconfigure
build/cc-auto.mak.in
pjsip-apps/build/Samples.mak

Hi Richard (picking you for this PR as you know about PJSIP and best practices when it comes to build infrastructure), 
I've made some tweaks to the PJSIP build infrastructure to make it compatible with different compiler's and tools. The issue before was that PJSIP defined `CC` as `gcc -c`, which means if you try to override `CC` (e.g. when running an analysis tool) everything goes wrong as the tool tries to compile to executables rather than object files. I've changed this so that `CC` just points to the compiler, and the `-c` is passed in the flags parameter. 
Please could you review? I'm not sure this is the right way of doing but if you have a better suggestion then I'm open to it.

Make pjsip compatible with different compilers / tools

---

pjsip/src/pjsip/sip_transport_tcp.c

Log what host we've failed to connect to.
This is a fix for https://github.com/Metaswitch/clearwater-issues/issues/2223
(I did my best to match existing indentation, which is 1 tab and 4 spaces (!) for the 2nd indent)
Tested live: we see logs like
```
19-06-2017 15:37:22.418 UTC Warning pjsip: tcpc0x7fb62004 TCP connect() error: Operation timed out (PJ_ETIMEDOUT) [code=70009]
19-06-2017 15:37:22.418 UTC Warning pjsip: tcpc0x7fb62004 Unable to connect to 5.6.7.8:5060
```
Also double-checked that `make full_test` passes in sprout

[Reviewer: Richard] Improve TCP connect() error log

---

pjsip/src/pjsip/sip_parser.c

Alex,
You tightened up the PJSIP parser of username and passwords, so I think you are the right person to review this change.
This change allows # symbols in them.

[Reviewer: Alex] Allow a hash in the username of a SIP URI

---

pjsip/src/pjsip/sip_parser.c

There was a bug in pjsip.
When a sip/tel uri is in the request header, the header is parsed into three pieces correctly:
ex. "MESSAGE sip:123 SIP/2.0" is broken into "MESSAGE" "sip:123" "SIP/2.0"
When a different uri was in the request header, it was broken down wrong:
ex. "MESSAGE urn:service:sos SIP/2.0" was broken into "MESSAGE" "urn:service:sos" " SIP/2.0"
The whitespace before the "SIP/2.0" meant the parsing failed.
This whitespace is now being stripped.

Fix pjsip bug that meant whitespace was not stripped for non sip or tel uris

---

pjsip/src/pjsip/sip_multipart.c

Hi Richard
Can you review this change for me?  Its the fix we worked on last week to ensure that one and only one Content-Type header makes it into the serialised form of a multipart SIP message.
UT is in the sprout PR (to be created shortly) and I've tested live by checking that a 3rd party REGISTER with included Req and Resp bodyparts has the expected "message/sip" Content-Type header in its bodyparts

[Reviewer RJW2] Multipart messages need (one) content type header in each part

---

pjsip/src/pjsip/sip_transaction.c
pjsip/src/pjsip/sip_transport.c
pjsip/src/pjsip/sip_transport_tcp.c

We don't want any per call output appearing in default level trace.  
This downgrades logs which have been spotted at default level trace.  I haven't been through and exhaustively searched for potential other instances - given a lack of pjsip knowhow I don't think I'm the right person to do this

[Reviewer: HJS] Downgrade per call error trace

---

pjlib/src/pj/ioqueue_epoll.c
pjlib/src/pj/timer.c

Some code has been added to pjsip to find blocking tasks that are being carried out on the transport thread, by logging a warning whenever the transport thread takes over X microseconds to handle an event/callback.
Placeholders for the threshold of 2,000 and 1,000 microseconds for logging the warnings have been put into this code, however I am currently looking into the longest times that it takes to handle an event/callback, so these numbers may be changed in the future.
The live tests passed when this code was included.
Here is an example of a log that showed up when the code was live tested, from handling an event:
`11-10-2017 11:27:17.689 UTC Warning pjsip:      ioq_epoll The transport thread spent 2087 microseconds processing an event.`
Here is an example of a log that showed up when …

Find blocking events on the transport thread

---

pjlib/src/pj/ioqueue_epoll.c
pjlib/src/pj/timer.c

The log for when the PJSIP transport thread takes to long to process a message or a callback is too spammy
as the thread occasionally needs to wait on a lock. Lower the severity so it isn't printed by default.

Lower severity of "slow transport thread" log

---

pjsip/include/pjsip/sip_msg.h
pjsip/src/pjsip/sip_msg.c

Moves a function into a header so that I can call it from sprout.

[Reviewer: KH1] Expose pjsip_generic_array_hdr_print

---

pjsip/include/pjsip/sip_multipart.h
pjsip/src/pjsip/sip_multipart.c

Hi Krista,
Please could you review this small PR.
For the registration sender UTs that I'm adding, I want to check the multipart bodies of 3rd party registers.
To do that, I need access to the `multipart_data` struct in PJSIP. This PR moves the definition of that struct to a header file so I can access it from sprout.
To avoid managing submodule changes on the SDM branch, I want to merge this straight into master since it's such a small change. Once this is merged, I'll send through the Registration Sender changes.
Thanks,
Sathiyan

[Reviewer: KH1] Move definition of multipart_data struct to header
